services:
  - type: web
    name: tcps-inc
    env: node
    plan: free
    region: oregon
    buildCommand: |
      npm install
      cd client && npm install && npm run build && cd ..
      npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
